# Column Configuration
# Edit 'in_use', 'rename', and 'new_name' as needed

COLUMNS = [
    {"name": "event_key", "in_use": True, "rename": False, "new_name": "event_key"},
    {"name": "event_date", "in_use": True, "rename": False, "new_name": "event_date"},
    {"name": "event_time", "in_use": True, "rename": False, "new_name": "event_time"},
    {
        "name": "event_first_player",
        "in_use": True,
        "rename": False,
        "new_name": "event_first_player",
    },
    {
        "name": "first_player_key",
        "in_use": True,
        "rename": False,
        "new_name": "first_player_key",
    },
    {
        "name": "event_second_player",
        "in_use": True,
        "rename": False,
        "new_name": "event_second_player",
    },
    {
        "name": "second_player_key",
        "in_use": True,
        "rename": False,
        "new_name": "second_player_key",
    },
    {
        "name": "event_final_result",
        "in_use": False,
        "rename": False,
        "new_name": "event_final_result",
    },
    {
        "name": "event_game_result",
        "in_use": False,
        "rename": False,
        "new_name": "event_game_result",
    },
    {
        "name": "event_serve",
        "in_use": False,
        "rename": False,
        "new_name": "event_serve",
    },
    {
        "name": "event_winner",
        "in_use": False,
        "rename": False,
        "new_name": "event_winner",
    },
    {
        "name": "event_status",
        "in_use": False,
        "rename": False,
        "new_name": "event_status",
    },
    {
        "name": "event_type_type",
        "in_use": True,
        "rename": False,
        "new_name": "event_type_type",
    },
    {
        "name": "tournament_name",
        "in_use": True,
        "rename": False,
        "new_name": "tournament_name",
    },
    {
        "name": "tournament_key",
        "in_use": True,
        "rename": False,
        "new_name": "tournament_key",
    },
    {
        "name": "tournament_round",
        "in_use": True,
        "rename": False,
        "new_name": "tournament_round",
    },
    {
        "name": "tournament_season",
        "in_use": True,
        "rename": False,
        "new_name": "tournament_season",
    },
    {"name": "event_live", "in_use": False, "rename": False, "new_name": "event_live"},
    {
        "name": "event_qualification",
        "in_use": False,
        "rename": False,
        "new_name": "event_qualification",
    },
    {
        "name": "event_first_player_logo",
        "in_use": False,
        "rename": False,
        "new_name": "event_first_player_logo",
    },
    {
        "name": "event_second_player_logo",
        "in_use": False,
        "rename": False,
        "new_name": "event_second_player_logo",
    },
    {
        "name": "download_time",
        "in_use": True,
        "rename": False,
        "new_name": "download_time",
    },
    {
        "name": "total_first_player_key",
        "in_use": True,
        "rename": False,
        "new_name": "total_first_player_key",
    },
    {
        "name": "total_second_player_key",
        "in_use": True,
        "rename": False,
        "new_name": "total_second_player_key",
    },
    {
        "name": "tournament_sourface",
        "in_use": True,
        "rename": True,
        "new_name": "sourface",
    },
    {
        "name": "results_for_player_key",
        "in_use": True,
        "rename": True,
        "new_name": "j1_key",
    },
    {"name": "won_main_player", "in_use": True, "rename": True, "new_name": "j1_wins"},
    {
        "name": "lost_main_player",
        "in_use": True,
        "rename": True,
        "new_name": "j1_losses",
    },
    {
        "name": "event_key_first",
        "in_use": False,
        "rename": False,
        "new_name": "j1_total_played",
    },
    {
        "name": "results_for_player_key_second",
        "in_use": True,
        "rename": True,
        "new_name": "j2_key",
    },
    {
        "name": "won_main_player_second",
        "in_use": True,
        "rename": True,
        "new_name": "j2_wins",
    },
    {
        "name": "lost_main_player_second",
        "in_use": True,
        "rename": True,
        "new_name": "j2_losses",
    },
    {
        "name": "event_key_second",
        "in_use": False,
        "rename": False,
        "new_name": "j2_total_played",
    },
    {
        "name": "results_for_player_key_first_surface",
        "in_use": True,
        "rename": True,
        "new_name": "j1_key_by_surface",
    },
    {
        "name": "won_main_player_first_surface",
        "in_use": True,
        "rename": True,
        "new_name": "j1_wins_by_surface",
    },
    {
        "name": "lost_main_player_first_surface",
        "in_use": True,
        "rename": True,
        "new_name": "j1_losses_by_surface",
    },
    {
        "name": "event_key_first_surface",
        "in_use": False,
        "rename": False,
        "new_name": "j1_total_played_by_surface",
    },
    {
        "name": "results_for_player_key_second_surface",
        "in_use": True,
        "rename": True,
        "new_name": "j2_key_by_surface",
    },
    {
        "name": "won_main_player_second_surface",
        "in_use": True,
        "rename": True,
        "new_name": "j2_wins_by_surface",
    },
    {
        "name": "lost_main_player_second_surface",
        "in_use": True,
        "rename": True,
        "new_name": "j2_losses_by_surface",
    },
    {
        "name": "event_key_second_surface",
        "in_use": False,
        "rename": False,
        "new_name": "j2_total_played_by_surface",
    },
    {"name": "player_key", "in_use": True, "rename": True, "new_name": "j1_key_points"},
    {"name": "points", "in_use": True, "rename": True, "new_name": "j1_points"},
    {
        "name": "player_key_second_standing",
        "in_use": True,
        "rename": True,
        "new_name": "j2_key_points",
    },
    {
        "name": "points_second_standing",
        "in_use": True,
        "rename": True,
        "new_name": "j2_points",
    },
]
